### ISSUE TITLE
GOG Unreal Tournament 2004 bad chunk magic

### ISSUE THREAD

**Issue by lazycrypt** [dscharrer/innoextract#82] opened 2019-04-08 13:34 UTC
I've tried to extract the Unreal Tournament 2004 installer file however I keep getting the following error: 
```
e:\Programs\innoextract>innoextract.exe "e:\Downloads\unreal_tournament_2004_ece\setup_unreal_tournament_2004_1.0_(18947).exe"
Extracting "Unreal Tournament 2004" - setup data version 5.5.7 (unicode)
 - "tmp\EULA.txt" [temp] - overwritten
 - "app\goggame-1207658691.ico" - overwritten
 - "app\Prefabs\"
Opening "e:\Downloads\unreal_tournament_2004_ece\setup_unreal_tournament_2004_1.0_(18947)-1.bin"
Stream error while extracting files!
 └─ error reason: bad chunk magic
If you are sure the setup file is not corrupted, consider
filing a bug report at http://innoextract.constexpr.org/issues
Done with 1 error.
```

Mind you if I run the installer and enable file integrity check it installs just fine without errors.

These are the file MD5 checksums:

> 2bef5dd25136ef670c64acbf0ae8ce2a *setup_unreal_tournament_2004_1.0_(18947)-1.bin
> 84bd6a14fa5b96d1d6425701f09d3280 *setup_unreal_tournament_2004_1.0_(18947).exe

**Comment by dscharrer** [comment] 2019-05-27 23:13
https://www.gog.com/game/unreal_tournament_2004_ece seems to be unavailable for me and I haven't been able to find another game with this issue. Have you noticed this with anything else?

**Comment by dscharrer** [comment] 2019-05-27 23:17
How large is the .bin file? Perhaps this is a duplicate of #68.

**Comment by lazycrypt** [comment] 2019-05-28 09:40
It's 2,425,859,115 bytes (~2.25GB). I just tried the dev snapshot build and it extracted the files without issue.

**Comment by dscharrer** [comment] 2019-08-29 22:46
Alright, closing as duplicate then.

**Closed by dscharrer** 2019-08-29 22:46 UTC
Labels: bug, needinfo
