### ISSUE TITLE
Myst: Masterpiece Edition from GOG extracts with missing files

### ISSUE THREAD

**Issue by Mister-Dolus** [dscharrer/innoextract#61] opened 2018-06-04 17:12 UTC
No error message shows in the terminal, but most of the files in the QTW directory are missing whenever I try to extract the game. I'm certain this installer if fine since it had all the needed files for ScummVM when I installed it via Wine. 

OS: Ubuntu Mate 18.04

**Comment by dscharrer** [comment] 2018-06-04 21:28
Please post the full terminal output.

**Comment by dscharrer** [comment] 2018-06-09 02:43
Assuming this is a duplicate of issue #58 until further information is provided.

**Closed by dscharrer** 2018-06-09 02:43 UTC
Labels: bug
