### ISSUE TITLE
Some new GOG installers incompatible with v1.7 (Win)

### ISSUE THREAD

**Issue by sombeot** [dscharrer/innoextract#70] opened 2018-07-16 14:56 UTC
Many of the latest GOG installers (from late April forward) are reporting "bad chunk magic" when attempting to extract offline setup files (possibly only those that are multi-part archives). This occurs with v1.7 (and the dev build of v1.8) of the Windows binary.

I have tried with and without the --gog/-g flag. Here is an example:

innoextract -d baldur setup_baldurs_gate_enhanced_edition_2.3.67.3_(b)(20125).exe
Extracting "Baldur's Gate - Enhanced Edition" - setup data version 5.5.7 (unicode)
Opening "setup_baldurs_gate_enhanced_edition_2.3.67.3(b)_(20125)-1.bin"
Stream error while extracting files!
└─ error reason: bad chunk magic
If you are sure the setup file is not corrupted, consider
filing a bug report at http://innoextract.constexpr.org/issues
Done with 1 error.

I am fairly certain that the files are not corrupt (they install properly and I have redownloaded them to be sure), and I have run into the issue with numerous games.

Here are a few examples of installers that do not successfully unpack and report "bad chunk magic" (note: I have made certain they are the latest releases):

Baldur's Gate Enhanced Edition: setup_baldurs_gate_enhanced_edition_2.3.67.3_(b)(20125).exe [+ 1 bin file]
Firewatch: setup_firewatch_1.09(20935).exe [+ 1 bin file]
The Saboteur: setup_the_saboteur_1.3_hotfix_(22140).exe [+ 2 bin files]
Tacoma: setup_tacoma_051518_(20769).exe [+ 1 bin file]
Riven: setup_riven_-the_sequel_to_myst_1.2_svm_update2(21923).exe [+ 1 bin file]
Gabriel Knight 2: setup_gabriel_knight_2_-the_beast_within_1.1(20239).exe [+ 1 bin file]
Vampire the Masquerade - Bloodlines: setup_vampire_the_masquerade_-_bloodlines_1.2_(up_10.0)_(22135).exe [+ 1 bin file]
The Feeble Files: setup_the_feeble_files_1.0_(20270).exe [+ 1 bin file]
The Whispered World: setup_the_whispered_world_se_3.2.0419_(16237).exe [+ 1 bin file]

In cases where GOG has only updated the ScummVM emulator in the archives, innoextract unpacks most of those fine. For example, the Sierra games, the Legend of Kyrandia series, the Myst games, etc. - with the 2 exceptions mentioned above (Riven & Gabriel Knight 2).

And some of the new installers are multi-part and do not have problems unpacking (e.g., Phantasmagoria 1+2).

I have little to no programming knowledge, so hope this information helps in some way. While this could potentially be user error, I have used innoextract for a few years without issue.

Thank you for your time and for all of your hard work.

**Comment by abduja** [comment] 2018-07-28 09:30
can confirm with this game https://www.gog.com/game/shaqfu_a_legend_reborn
setup_shaq-fu_a_legend_reborn_1.0_(21254).exe [crc32: 5c39555a]
setup_shaq-fu_a_legend_reborn_1.0_(21254)-1.bin [crc32: 51846614]
Inno Setup version 5.5.9 (u)
Stream error while extracting files!
 └─ error reason: bad chunk magic
If you are sure the setup file is not corrupted, consider
filing a bug report at http://innoextract.constexpr.org/issues
Done with 1 error.

**Comment by dscharrer** [comment] 2018-09-09 12:59
Duplicate of issue #68. This has been fixed in the [latest development snapshot](http://constexpr.org/innoextract/files/snapshots/innoextract-1.8-dev-2018-09-09/).

**Closed by dscharrer** 2018-09-09 12:59 UTC
