### ISSUE TITLE
error while unpacking. 

### ISSUE THREAD

**Issue by rewolff** [dscharrer/innoextract#92] opened 2019-07-25 05:02 UTC
Hi, 
I downloaded hte SDK from http://www.isomet.com/software.html and wanted to extract the files. 
When I do so: 
```
arning: Unexpected setup data version: 6.0.0 (unicode)
Warning: Unexpected Auto Boolean value: 10
Warning: Unexpected Architecture flags: 10
Stream error while parsing setup headers!
 ├─ detected setup version: 6.0.0 (unicode)
 └─ error reason: basic_ios::clear: iostream error
If you are sure the setup file is not corrupted, consider 
filing a bug report at http://innoextract.constexpr.org/issues
Done with 1 error and 3 warnings.
```
Because I'm pretty sure that my file is correct (I tried both the W7 and W10 version and got identical errors) I'nm following the suggestion to file a bugreport.

**Comment by rewolff** [comment] 2019-07-25 05:05
Update: at first I was expecting that this file simply isn't one meant to be handled by innoextract. However someone suggested using exiftool on the file and it confirms my "I wouldn't have thought so" suspicion that it is indeed an inno-setup program!

**Comment by rewolff** [comment] 2019-07-25 05:15
Update: Curretn git vrsion extracts this wihtout complaints.

**Comment by dscharrer** [comment] 2019-07-25 05:40
Duplicate of issue #83

**Closed by dscharrer** 2019-07-25 05:40 UTC
Labels: duplicate
